blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/rafaelqsantos-rqs/openparquet/discussions
    about: Por favor, fa√ßa perguntas e discuta ideias aqui antes de abrir uma issue.