name: Audit Code

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev libssl-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Frontend Deps
        run: npm ci

      - name: Check TypeScript/Svelte
        run: npm run check

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Rust Code (Clippy)
        working-directory: ./src-tauri
        run: cargo clippy -- -D warnings
